<a href="https://colab.research.google.com/github/Anish-Codeth/Anish-Codeth/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
torch.__version__

'2.3.0+cu121'

## introduction to tensor

!nvidia-smi


In [ ]:
scalar=torch.tensor(7)
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

#matrix

In [ ]:
matrix=torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
tensor=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor.shape)

torch.Size([2, 2, 3])


### random tensors

In [ ]:
tensor=torch.rand((3,4))
tensor

tensor([[0.8930, 0.0082, 0.5126, 0.3431],
        [0.8216, 0.1777, 0.7116, 0.8469],
        [0.1713, 0.0118, 0.2411, 0.6324]])

In [ ]:
 random_size_image=torch.rand((244,244,3))
 print(random_size_image.shape)

torch.Size([244, 244, 3])


### zersos and ones

In [ ]:
rand_ones=torch.ones((3,3))
rand_ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
rand_ones.dtype

torch.float32

### range

In [ ]:
one_ten=torch.arange(1,11,2)
one_ten

tensor([1, 3, 5, 7, 9])

In [ ]:
torch.zeros_like(one_ten)

tensor([0, 0, 0, 0, 0])

### tensor datatype

In [ ]:
float_16=torch.tensor([1,2,3],dtype=torch.float32,device="cpu",requires_grad=False)
float_32=float_16.type(torch.float32)
unknown=float_16*float_32
unknown.dtype

torch.float32

In [ ]:
one_ten.dtype

torch.int64

In [ ]:
torch.tensor([1,2,3],dtype=torch.int32)*torch.tensor([1,2,3],dtype=torch.float32)

tensor([1., 4., 9.])

In [ ]:
one_ten.device

device(type='cpu')

## maipulating tensors

In [ ]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
%%time
torch.manual_seed(42)
tensor1=torch.rand((2,3))
tensor2=torch.rand((3,2))
torch.matmul(tensor1,tensor2)

CPU times: user 3.67 ms, sys: 59 µs, total: 3.73 ms
Wall time: 4.76 ms


tensor([[1.4450, 1.0493],
        [1.1750, 1.1700]])

In [ ]:
%%time
value=0
tensor3=torch.rand((2,2))
for i in range(tensor1.shape[0]):
  for j in range(tensor2.shape[1]):
    temp=1
    for k in range(tensor1.shape[1]):
      temp*=tensor1[i][k]*tensor2[k][j]
    tensor3[i][j]=temp
tensor3


CPU times: user 1.09 ms, sys: 0 ns, total: 1.09 ms
Wall time: 1.1 ms


tensor([[0.0697, 0.0194],
        [0.0508, 0.0141]])

In [ ]:
a=torch.rand((3,2))
b=torch.rand((3,2))
torch.matmul(a,b.Tf)

AttributeError: 'Tensor' object has no attribute 'Tf'

In [ ]:
x=torch.arange(1,100,1)
x.dtype

torch.int64

In [ ]:
x=x.type(torch.float32)
x.mean(),x.sum()

(tensor(50.), tensor(4950.))

## aggresgation fumction

In [ ]:
a=torch.rand((3,2))
a,a.min(dim=0)


(tensor([[0.4425, 0.0958],
         [0.6142, 0.0573],
         [0.5657, 0.5332]]),
 torch.return_types.min(
 values=tensor([0.4425, 0.0573]),
 indices=tensor([0, 1])))

## reshaping,stacking,squeeezing,unsqueezing

In [ ]:

torch.manual_seed(2)
a=torch.rand((3,2,1))
a

tensor([[[0.6147],
         [0.3810]],

        [[0.6371],
         [0.4745]],

        [[0.7136],
         [0.6190]]])

In [ ]:
x=torch.arange(1.,10.)
x.shape

torch.Size([9])

In [ ]:
x_reshape=x.reshape(3,3)
x_reshape

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
x_view=x.view((1,9))
id(x_view),id(x),id(x_reshape),x.storage().data_ptr(),x_view.storage().data_ptr()f

(134539330259280,
 134539330270560,
 134539330267360,
 101808171797312,
 101808171797312)

In [ ]:
#stack
x=torch.randn(3)
print(x.shape)
x_stacked=torch.stack([x,x],dim=1)
x_stacked

torch.Size([3])


tensor([[-0.3628, -0.3628],
        [-1.0494, -1.0494],
        [-1.0264, -1.0264]])

In [ ]:
x=torch.rand((3,2,1))
squeezed=x.squeeze()
print(squeezed.unsqueeze(dim=2).shape)

torch.Size([3, 2, 1])


In [ ]:
a=torch.rand((2,3))
print(a)
print(a.permute((1,0)),a.T)

tensor([[0.5737, 0.3445, 0.6369],
        [0.9621, 0.5273, 0.1573]])
tensor([[0.5737, 0.9621],
        [0.3445, 0.5273],
        [0.6369, 0.1573]]) tensor([[0.5737, 0.9621],
        [0.3445, 0.5273],
        [0.6369, 0.1573]])


In [ ]:
images=torch.rand((224,224,3))
# indexing with pytorch
images[1:3][0]

## pytorch and numpy

In [ ]:
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array).type(torch.float32)## when converting from numpy to tensor it becomes float64
array+=1
tensor


tensor([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
#torch into numpy
tensor=torch.ones((3,3))
array=tensor.numpy()
array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

## reproducibility

In [ ]:
import torch

random_seed=99
torch.manual_seed(random_seed)
a=torch.rand(3,4)


b=torch.rand(3,4)
print(a)
print(b)

tensor([[0.1033, 0.9702, 0.9481, 0.9787],
        [0.3268, 0.9200, 0.0503, 0.4583],
        [0.8608, 0.4882, 0.7981, 0.2011]])
tensor([[0.1914, 0.8979, 0.9541, 0.5242],
        [0.6006, 0.9888, 0.7474, 0.5498],
        [0.0670, 0.1168, 0.1724, 0.9940]])


## GPU

In [ ]:
## getting a gpu
! pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu118
INFO: pip is looking at multiple versions of torch to determine which version is compatible with other requirements. This could take a while.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 839.7/839.7 MB 1.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.2/23.2 MB 21.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 875.6/875.6 kB 36.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 29.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 728.5/728.5 MB 1.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 417.9/417.9 MB 2.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.4/168.4 MB 5.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.1/58.1 MB 9.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 MB 6.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.1/204.1 MB 6.2

In [ ]:
!nvidia-smi

Wed Jun  5 01:55:54 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device="cuda" if torch.cuda.is_available() else 'cpu'
device

'cuda'

## how to use gpu

In [ ]:
tensor=torch.tensor([1,2,3],device="cpu")
print(tensor.device)

cpu


In [ ]:
tensor_gpu=tensor.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor_cpu=tensor.to("cpu").numpy()## numpy can't be in gpu
tensor_cpu

array([1, 2, 3])

# QUESTIN AND ANSWER  

In [ ]:
import torch
tensor1=torch.rand((7,7))
tensor2=torch.rand((1,7))
prod=torch.matmul(tensor1,tensor2.T)

In [ ]:
torch.manual_seed(0)
tensor1=torch.rand((7,7))
tensor2=torch.rand((1,7))
prod=torch.matmul(tensor1,tensor2.T)

In [ ]:
torch.cuda.manual_seed(0)
a=torch.rand((2,3))
b=torch.rand((2,3))
a_gpu=a.to('cuda')
b_gpu=b.to('cuda')
prod=torch.matmul(a_gpu,b_gpu.T)
prod

tensor([[1.7488, 0.6094],
        [1.4999, 0.5721]], device='cuda:0')

In [ ]:
max_val=prod.max()
min_val=prod.min()
print(max_val,min_val)

tensor(1.7488, device='cuda:0') tensor(0.5721, device='cuda:0')


In [ ]:
torch.manual_seed(7)
a=torch.rand((1,1,1,10))
b=a.squeeze()
print(a.shape,b.shape)

torch.Size([1, 1, 1, 10]) torch.Size([10])


## extra curruculum

In [2]:
import torch